language: node_js
node_js:
  - "lts/*"
script: npm run-script build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "naOSytY7Gh/h/opuSigpwMIHL24/UkcCbSfQy+LKfEHkGUi1a24MZJCI7WRYeyCMkj5ZQQVlw0lktNxtI0ilAT/W95G1O/V9/sfH9vi1lJTyFjmIWwFk9rdxK5k4MXr4RPTuYW0t4eLsLhLBLZRHv0rYkXS/oo3eRN/va+xX6QMtqahc2xpzahXgVHKrD/YwVB4NK+aK6BAZoEPWR5mIEwPOah2I8AHEBUtDEXE2fKkORoNEQBCBFSb77fvJacz/ZQdqXhITaWgrfovc0MRURCBg4NeHmY6zxq+GpWjBmuMp0c8hSIr0Va54qHvHlNoGuTr09Q1fHD/BWd+rO6gFi3yHtLSGm5tJ3Nth+5lNKSTQINjSXjiVj8rWCtT32vNY5A1B91foLy5dn2Eur1ro9Wue5V2aOQhLnTKNJu6vYQiGxKxV13Lac/CX8F39TfInNecNM97IFf8nTk4Rkv4JPI8y7TSr+8UEJuVwa8S7JKXn4Q4LfhtGocYk90J2lrcsil9QeY2BkmUFsivqf9zvThE7n4DDjWXql4GWOTRWraLv0u9i3XzjJiqFWQy8gIuu6eEaWIwHkkO0UntmYbCsaYIV95HrK4A4+m2G/M4TwaAxRTwoBBkUKlFS1QI+ML9D/2BzpIF7kyWRSwCsIQc1Kubb4ljuDZo/IA1js0g6wp8="
  on:
    branch: master 
notifications:
  email: false
